version: "3.7"

services:
    db:
        image: postgres
        container_name: ignite-nodejs-desafio-05
        restart: always
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=queries_challenge
        volumes:
            - pgdata:/data/postgres
volumes:
    pgdata:
        driver: local